services:
  opengist:
    container_name: ${OPENGIST_CONTAINER_NAME}
    image: ${OPENGIST_IMAGE_NAME}:${OPENGIST_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - TZ=${TIMEZONE}
    ports:
      - ${OPENGIST_HTTP_PORT}:6157
      - ${OPENGIST_SSH_PORT}:2222
    volumes:
      - ${OPENGIST_DATA_PATH}:/opengist
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6157"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}

networks:
  default:
    name: opengist_network
    driver: bridge

volumes:
  default:
    name: opengist_data
    driver: local